version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.5.1

jobs:
  build-test:
    docker:
      - image: cimg/node:16.6.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test

  stage:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.17.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME

workflows:
  build-deploy:
    jobs:
      - build-test
      - stage:
          requires:
            - build-test
          filters:
            branches:
              only: main
      - test:
          requires:
            - stage
      - deploy:
          requires:
            - test
